NUMPY

In [1]:
#import numpy library
import numpy as np

In [2]:
#first numpy array
#regular array: mention elements within square brackets
first_numpy_array = np.array([45, 90, 74, 23]) #choose variable name such that they are self explanatory.

In [3]:
#print array
print (first_numpy_array)

[45 90 74 23]


In [4]:
#array with zeros
#zeros array: mention shape of element within parenthesis
array_with_zeros = np.zeros((2, 2))
print(array_with_zeros)


[[0. 0.]
 [0. 0.]]


In [5]:
#array with ones
array_with_ones = np.ones((4, 4))
array_with_ones #this will also show the array output

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
#array with empty
#note: this will contain random numbers until you set it manually
array_with_empty = np.empty((2, 4)) 
array_with_empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.82599983e-321, 1.78019082e-306,
        1.37959740e-306]])

In [7]:
#array with arange
arange_array = np.arange(8)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
#reshape method to change or create array
arange_array.reshape(4, -1) # 8 = 2*4, cannot give random shape
#if you give -1 as parameter in reshape it will fill the position of -1 operator into valid size if possible along with another parameter else error

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [9]:
#linspace for linearly(equal) spaced data elements
linspace_array = np.linspace(5, 25, 7) #syntax: np.linspace(firstEle, lastEle, totalEquidistEle)
linspace_array

array([ 5.        ,  8.33333333, 11.66666667, 15.        , 18.33333333,
       21.66666667, 25.        ])

ARITHMETIC OPERATIONS

In [10]:
a = np.array([[5, 3, 1], [2, 6, 8]])
b = np.array([3, 7, 2])

In [11]:
#addition
np.add(a, b)

array([[ 8, 10,  3],
       [ 5, 13, 10]])

In [12]:
#subtract
np.subtract(b, a)

array([[-2,  4,  1],
       [ 1,  1, -6]])

In [13]:
#multiply
np.multiply(a, b)

array([[15, 21,  2],
       [ 6, 42, 16]])

In [14]:
#divide
np.divide(a, b)

array([[1.66666667, 0.42857143, 0.5       ],
       [0.66666667, 0.85714286, 4.        ]])

In [15]:
#power
np.power(a, 3) #it can also be matrix to matrix

array([[125,  27,   1],
       [  8, 216, 512]], dtype=int32)

conditional statements

In [16]:
arr = np.array([7, 0, 3, 4, 9, 5, 8, 2])

In [18]:
#where 
np.where(arr%2 == 0, "even", "odd") #(condition, if statement, else statement)

array(['odd', 'even', 'odd', 'even', 'odd', 'odd', 'even', 'even'],
      dtype='<U4')

In [19]:
#select
conditionlist = [arr%3==0, arr%2==0]
choicelist = [arr*3, arr**2]
np.select(conditionlist, choicelist, default="123")

array(['123', '0', '9', '16', '27', '123', '64', '4'], dtype='<U11')