In [1]:
#import numpy library
import numpy as np

In [2]:
#first numpy array
#regular array: mention elements within square brackets
first_numpy_array = np.array([45, 90, 74, 23]) #choose variable name such that they are self explanatory.

In [3]:
#print array
print (first_numpy_array)

[45 90 74 23]


In [5]:
#array with zeros
#zeros array: mention shape of element within parenthesis
array_with_zeros = np.zeros((2, 2))
print(array_with_zeros)


[[0. 0.]
 [0. 0.]]


In [6]:
#array with ones
array_with_ones = np.ones((4, 4))
array_with_ones #this will also show the array output

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#array with empty
#note: this will contain random numbers until you set it manually
array_with_empty = np.empty((2, 4)) 
array_with_empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 3.99205042e-321, 1.35807731e-311,
        1.35807731e-311]])

In [15]:
#array with arange
arange_array = np.arange(8)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
#reshape method to change or create array
arange_array.reshape(-1) # 8 = 2*4, cannot give random shape
#if you give -1 as parameter in reshape it will fill the position of -1 operator into valid size

NameError: name 'arange_array' is not defined

In [22]:
#linspace for linearly(equal) spaced data elements
linspace_array = np.linspace(5, 25, 7) #syntax: np.linspace(firstEle, lastEle, totalEquidistEle)
linspace_array

array([ 5.        ,  8.33333333, 11.66666667, 15.        , 18.33333333,
       21.66666667, 25.        ])