NUMPY

In [1]:
#import numpy library
import numpy as np

In [2]:
#first numpy array
#regular array: mention elements within square brackets
first_numpy_array = np.array([45, 90, 74, 23]) #choose variable name such that they are self explanatory.

In [3]:
#print array
print (first_numpy_array)

[45 90 74 23]


In [4]:
#array with zeros
#zeros array: mention shape of element within parenthesis
array_with_zeros = np.zeros((2, 2))
print(array_with_zeros)


[[0. 0.]
 [0. 0.]]


In [5]:
#array with ones
array_with_ones = np.ones((4, 4))
array_with_ones #this will also show the array output

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
#array with empty
#note: this will contain random numbers until you set it manually
array_with_empty = np.empty((2, 4)) 
array_with_empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.82599983e-321, 1.78019082e-306,
        1.37959740e-306]])

In [7]:
#array with arange
arange_array = np.arange(8)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
#reshape method to change or create array
arange_array.reshape(4, -1) # 8 = 2*4, cannot give random shape
#if you give -1 as parameter in reshape it will fill the position of -1 operator into valid size if possible along with another parameter else error

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [9]:
#linspace for linearly(equal) spaced data elements
linspace_array = np.linspace(5, 25, 7) #syntax: np.linspace(firstEle, lastEle, totalEquidistEle)
linspace_array

array([ 5.        ,  8.33333333, 11.66666667, 15.        , 18.33333333,
       21.66666667, 25.        ])

ARITHMETIC OPERATIONS

In [10]:
a = np.array([[5, 3, 1], [2, 6, 8]])
b = np.array([3, 7, 2])

In [11]:
#addition
np.add(a, b)

array([[ 8, 10,  3],
       [ 5, 13, 10]])

In [12]:
#subtract
np.subtract(b, a)

array([[-2,  4,  1],
       [ 1,  1, -6]])

In [13]:
#multiply
np.multiply(a, b)

array([[15, 21,  2],
       [ 6, 42, 16]])

In [14]:
#divide
np.divide(a, b)

array([[1.66666667, 0.42857143, 0.5       ],
       [0.66666667, 0.85714286, 4.        ]])

In [15]:
#power
np.power(a, 3) #it can also be matrix to matrix

array([[125,  27,   1],
       [  8, 216, 512]], dtype=int32)

conditional statements

In [16]:
arr = np.array([7, 0, 3, 4, 9, 5, 8, 2])

In [18]:
#where 
np.where(arr%2 == 0, "even", "odd") #(condition, if statement, else statement)

array(['odd', 'even', 'odd', 'even', 'odd', 'odd', 'even', 'even'],
      dtype='<U4')

In [19]:
#select
conditionlist = [arr%3==0, arr%2==0]
choicelist = [arr*3, arr**2]
np.select(conditionlist, choicelist, default="123")

array(['123', '0', '9', '16', '27', '123', '64', '4'], dtype='<U11')

In [10]:
#mathematical and statistical functions
arr1 = np.array([[2, 3, 6],
                 [7, 0, 9],
                 [8, 1, 5]])

In [12]:
#finds minimum in entire array
np.min(arr1) 

0

In [13]:
#finds minimum from vertical columns
np.amin(arr1, axis=0)

array([2, 0, 5])

In [14]:
#finds minimum from horizontal cols
np.amin(arr1, axis=1)

array([2, 0, 1])

In [15]:
#similarly for maximum
print(np.max(arr1))
print(np.amax(arr1, axis=0))
print(np.amax(arr1, axis=1))

9
[8 3 9]
[6 9 8]


In [18]:
print (np.mean(arr1))
print (np.median(arr1))
print (np.std(arr1)) #std deviation
print (np.var(arr1)) #variance
print(np.percentile(arr1, 25)) #quartile deviation with values between 1 and 100

4.555555555555555
5.0
3.02254900194121
9.135802469135804
2.0


In [20]:
#trigonometric functions
array_degree_angles = np.array([0, 30, 45, 60, 90])
np.sin(array_degree_angles * np.pi/180) #since sine fn takes input in radians.

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [23]:
print(np.cos(array_degree_angles * np.pi/180))
print(np.tan(array_degree_angles * np.pi/180))
#inverse trig with arc prefix
print(np.arcsin(array_degree_angles * np.pi/180))
print(np.arccos(array_degree_angles * np.pi/180))
print(np.arctan(array_degree_angles * np.pi/180))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
[0.         0.55106958 0.90333911        nan        nan]
[1.57079633 1.01972674 0.66745722        nan        nan]
[0.         0.48234791 0.66577375 0.80844879 1.00388482]


C:\Users\NANDITHAPRABU\AppData\Local\Temp\ipykernel_20436\1730064207.py:4: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(array_degree_angles * np.pi/180))
C:\Users\NANDITHAPRABU\AppData\Local\Temp\ipykernel_20436\1730064207.py:5: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(array_degree_angles * np.pi/180))


In [25]:
#additional floor and ceil functions
fcarray = np.array([-6.48, -4.3, -0.8, 0.66, 2.82, 9.31])
print(np.floor(fcarray))
print(np.ceil(fcarray))

[-7. -5. -1.  0.  2.  9.]
[-6. -4. -0.  1.  3. 10.]


Indexing and slicing

In [26]:
#indexing
arr1d = np.array([2, 4, 9, 1])
arr2d = np.array([[7, 3, 1], 
                  [4, 0, 6]])
arr3d = np.array([[[1, 2, 3], 
                   [4, 5, 6]], 
                  [[7, 8, 9], 
                   [10, 11, 12]]])
print(arr1d[2])
print(arr2d[1, 1])
print(arr3d[1, 1, 1])

9
0
11


In [48]:
#slicing
#for nd array there will be n parameters
#each parameter can be an index or slice opr
print(arr1d[1:])
print([arr2d[1, 0:2]])
print([arr2d[0:1:3]])
print([arr2d[0:1, 1]]) 
print(arr3d[1:, 1:, 0:])

[4 9 1]
[array([4, 0])]
[array([[7, 3, 1]])]
[array([3])]
[[[10 11 12]]]
